baseURL = 'https://fra179.github.io/MCPLeaderboard/'
languageCode = 'en-us'
title = 'MCP 2025' # This is the customizable website name

[params]
  teacher_name = "Prof. De Sensi" # The Teacher Name

[taxonomies]
  technology = "technology"